### ISSUE TITLE
Payload too large error (http 413) when submitting the VQA demo.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#1033]
Sentry is sometimes showing an error that's occurring probably because the image being uploaded is too large:

https://sentry.io/organizations/ai2/issues/2169884626/?project=5599301&query=is%3Aunresolved

The error is a little hard to diagnose because in this situation we get a HTTP 413 with an HTML response. So the actual error that's thrown is something about not being able to parse the JSON response (because in this situation it's HTML).

We should show the user a helpful error when this occurs instead,.

**Comment by aimichal** [comment]
When I follow that link to sentry.io, I see that `/api/nmn/predict` returned a 500. (The root of that is `IndexError: list index out of range"`.) Maybe that returned HTML instead of JSON.


On the other hand, I did find a 413 requesting https://demo.allennlp.org/api/vilbert-vqa/predict (insertID `15ci3nwg15ymi3p`):

![image](https://user-images.githubusercontent.com/19393950/122828079-0aa03480-d29a-11eb-8ccb-17e0a1442ccd.png)

But `request_size: "436"` 🤔

**Comment by aimichal** [comment]
Peripherally related cosmetic fix: https://github.com/allenai/tugboat/pull/14

**Comment by aimichal** [comment]
On https://demo.allennlp.org/visual-question-answering I can drag-and-drop a 30MB JPEG file and see a nice little pop-up telling me to provide a smaller file:


> ![image](https://user-images.githubusercontent.com/19393950/122831930-72a54980-d29f-11eb-8271-036429f56a3d.png)

> ![image](https://user-images.githubusercontent.com/19393950/122832182-dc255800-d29f-11eb-8bba-d5832e4564b2.png)

This is preceded (I think, but may be followed) by an HTTP POST request for https://demo.allennlp.org/api/vilbert-vqa/noop with an HTTP header `content-length: 30144544`, and an HTTP response code of 413 and an HTML body (as you can see in the body).

In the console I see:

> ![image](https://user-images.githubusercontent.com/19393950/122832116-bdbf5c80-d29f-11eb-835b-888b9ac35128.png)

So from what I can tell, we have the right guards in place for large files, and a nice user-friendly message (besides the cosmetic issue I mentioned above).

So I _believe_ that the error on sentry.io above is because of an HTTP request for /predict which responds with an HTTP status 500 and an HTML body. Perhaps that isn't handled right.

**Comment by aimichal** [comment]
@codeviking The link you posted is for an error on `/api/nmn/predict`, not VQA.

From what I can tell, VQA's handling of large images is in tip-top shape. 🎩 

However, NMN causing 500s is a thing, for which I'll file as a separate thing.

**Comment by aimichal** [comment]
Here's the separate issue: https://github.com/allenai/allennlp-demo/issues/1035
