### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by aimichal** [allenai/allennlp-demo#1035]
https://sentry.io/organizations/ai2/issues/2169884626/?project=5599301&query=is%3Aunresolved shows that an HTTP 500 response from /api/nmn/predict resulted in a client-side error:

> SyntaxError: Unexpected token < in JSON at position 0

The reason for /api/nmn/predict to error on the server is "IndexError: list index out of range".

I'm not yet sure which of these is happening:

* From reading https://github.com/allenai/tugboat/blob/main/components/Promised.tsx I believe we're entering the block `if (state === PromiseState.Failure || !payload) { ... }` and both reporting the exception (`captureException`) and showing an error to the user (`<ErrorMessage />`).
* Or, perhaps the error is happening elsewhere, but still falls into this condition.
* Or, perhaps the error is happening elsewhere and results in only a console log message, and no good feedback to the user.

**Comment by codeviking** [comment]
FWIW we see a lot of these errors in Sentry, for multiple API endpoints.

I think part of the problem lies in the fact that the default response from the server is HTML. So if something happens and the server throws an error, it returns an HTML message when the client is expected JSON.  We then naively try to parse it as JSON (or code we rely on does), which in turn causes this error to be thrown.  This hides the actual problem -- that a request is failing.  

So at the very least we should see if we can resolve this so that our logs are more actionable. It's also possible that after resolving this we'll discover that the error is outside of our control (and related the model endpoint in question), which probably should be triaged separately by the AllenNLP team.

**Comment by aimichal** [comment]
Right, the client should be resilient to random server response, like HTML. Maybe this is to blame in ui/src/lib/ModelInfo.ts:

```js
/**
 * Fetch information for a specific model.
 */
export function fetchModelInfo(modelId: string): Promise<ModelInfo> {
    return fetch(`/api/${modelId}`).then((r) => r.json());
}
```

And yes, /api/nmn/predict 500ing should be fixed separately.

**Comment by aimichal** [comment]
Er, nevermind, that's for "model info", not the predict endpoint.

Probably somewhere in Tugboat. I'll scratch a bit more.

**Comment by aimichal** [comment]
https://github.com/allenai/allennlp-demo/pull/1036 should make the error more reasonable.

**Comment by aimichal** [comment]
This is released.
