### ISSUE TITLE
We need a cache breaker

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#21]
Currently the AllenNLP demo seems to cache aggressively.  If I release with a new model, I need to force refresh to see the option.  Similarly, if a model is used it continues to appear for the user as an option, and 404's on POST.

We need to break the cache on the demo so the user always sees the latest and the greatest.

**Comment by aaronsarnat** [comment]
This issue was *probably* fixed when [Modularizing CSS (#56)](https://github.com/allenai/allennlp-demo/pull/56) was merged, but that has not yet been verified. Will keep an eye on this and close the issue once I'm certain that React is doing this for us now.

**Comment by aaronsarnat** [comment]
@schmmd verified that we have this feature as a result of merging #56. Since I just merged changes to the CSS in #74, I was able to test this. You can see that the bundle is building `main.css` file with a new hash prefix. This forces the browser to pull down the latest styles as a separate resource since it sees it as a different file.

Closing this issue as fixed.

![image](https://user-images.githubusercontent.com/8367927/46044531-dfc82800-c0cf-11e8-8137-7a0fb986394c.png)
