### ISSUE TITLE
Running demo with my own model (would appreciate instructions)

### ISSUE THREAD

**Issue by dchang56** [allenai/allennlp-demo#282]
Hello,

I'm trying to run a demo of a BERT model (not an allennlp model) for multi-class classification (following the run_glue.py script in huggingface/transformers repo closely). 

I've gotten the demo to run locally using docker, but I'm not sure how to proceed. I'm not too familiar with Allennlp, and would greatly appreciate step-by-step instructions for running my model in the demo!

**Comment by dchang56** [comment]
@Eric-Wallace @matt-gardner

**Comment by Eric-Wallace** [comment]
Hi, sorry for the delay. We were attending EMNLP in Hong Kong. 

I think @sanjayss34 has done this before for a prior work, he would have good insights on doing so. @sanjayss34 could you remind me what you did?

@matt-gardner we should probably add instructions for generally converting pytorch transformers models into allennlp, since this seems to come up a lot.

**Comment by matt-gardner** [comment]
@dchang56, we didn't write the huggingface code, and I have no idea how you would take a huggingface model and put it into a demo.  We designed a `Predictor` abstraction for allennlp that made it easy to serve demos, but I don't know what APIs the huggingface code has to let you do similar things.  This isn't a question for the allennlp repo, it's a question for the transformers repo.  I'm closing this issue, but if you have a more specific question for allennlp, feel free to ask it.
