### ISSUE TITLE
[Feature] Make this pip installable? 

### ISSUE THREAD

**Issue by nicolasahar** [allenai/allennlp-demo#463]
Any plan on making the `allennlp-demo` pip installable? Would be useful for those looking to use it to serve AllenNLP models in their own application.

**Comment by matt-gardner** [comment]
No, we are not planning on making this pip installable.  Most of what's here is a flask application and UI components.  The actual models mostly come from `allennlp-models`, which is pip installable.  If you want to serve a model from here, I'd recommend copying/cloning what we do in this repo, instead of trying to pip install it.
