### ISSUE TITLE
masked language modeling input covers up answer

### ISSUE THREAD

**Issue by jonborchardt** [allenai/allennlp-demo#533]
start
![image](https://user-images.githubusercontent.com/8194065/93500316-fbcec080-f8c8-11ea-9b50-7f12f0542dc7.png)

add text and the answers go away and there is no progress indicator
![image](https://user-images.githubusercontent.com/8194065/93500593-2882d800-f8c9-11ea-8915-73e77f153ecc.png)

expected:
1- dont grow the input box on input
2- gray the answer area
3- add a progress indicator till there is an answer

**Comment by matt-gardner** [comment]
Having the textbox grow is indeed not ideal, but I'll note that there's no answer because there was no requested answer in here.  You need to have a `[MASK]` token in the input in order for the answer to show up.

So, I'll revise the "expected" to something like: `Have the answer area show "Enter a [MASK] token to see a prediction" when there is no [MASK] token in the input.`

**Comment by jonborchardt** [comment]
![image](https://user-images.githubusercontent.com/8194065/93504496-6afae380-f8ce-11ea-8754-db4f141a88f5.png)

**Comment by jonborchardt** [comment]
ya, if you have [MASK] it i bast enough for no progress indicator.  But still as design, its odd... we should just leave the answer space and make it blank if no answer yet (maybe add a message... 'Loading...')

and if there is no [MASK] remind the user to add one

**Comment by jonborchardt** [comment]
this is no longer an issue with the new code
