### ISSUE TITLE
Deliver a new AllenNLP demo (Tugboat).

### ISSUE THREAD

**Issue by jonborchardt** [allenai/allennlp-demo#700]
## External Doc:
[one'ish pager](https://docs.google.com/document/d/1v9XJEXwsIUVQ-CK0D1MyzXAa_LL4cpBcjDyLrWG25UI/edit#heading=h.nq7ni9gxukfv)

## Motivation: 

AllenNLP is our most popular demo, but the codebase is hard to extend.  We'd like to rebuild the UI to better serve AllenNLP, but with a general approach that we could also apply to Mosaic KG, the PRIOR demos, and other collections of demos.

## Success Criteria: 

* Sam and Jon sign off on the Tugboat Pattern used in AllenNLP demo
* We port over the following demos:
  - [x] Reading Comprehension
  - [x] Named Entity Recognition
  - [x] Open Information Extraction
  - [x] Semantic Role Labeling
  - [x] Dependency Parsing
  - [x] Constituency Parsing
  - [x] Coreference Resolution
  - [x] Textual Entailment
  - [x] Masked Language Modeling
  - [x] Visual Question Answering
  - [x] Sentiment Analysis
  - [x] Language Modeling

 * We've fixed some bugs as part of warranty work:
   - [x] Add a `<SingleModelDemo />` so that we don't end up with urls like: https://demo.allennlp.org/open-information-extraction/open-information-extraction
 * We have the following higher-level capabilities in place:
   - [x] We can capture client-side exceptions, so that we know when these failures occur.
   - [x] We have some sort of process for reviewing and acting on these exceptions as necessary.
 * The models in the previous list include model cards.
 * We've deleted the legacy code that's no longer used:
   - [x] Removed unused UI code
   - [x] Removed Permalinks API
   - [x] (We keeping GA for now) Removed Google Analytics
 * Update dependencies 
   - [x] Dependencies updated after all js code removed
 * There are some regressions that need to be addressed
   - [x] Training configuration URLs are fixed per task.
   - [x] Right now developing locally with a single model doesn't work with demos that use the updated UI code because the info route isn't ran locally.

## Updated Estimate:

We have removed some of the tasks, so this is what is remaining for q1
There are 13 demos in total, of which 2 are very hard, 3 are hard and 7 are easy, which means we expect this to take ```4-5 more weeks```.
- Hard
  - Reading comprehension (13 d) more than half done. (3d remaining)
  - Dependency Parsing (4 d)
- Medium
  - Coreference Resolution (3d)
  - Language Modeling (3d)
  - Masked language model (3d)
- Easy
  - The other 7, eg. VQA, Named Entity Recognition, etc… (0-2d each, 7d total)

## Related to:
* https://github.com/allenai/allennlp-demo/issues/527
* https://github.com/allenai/skiff/issues/798

**Comment by schmmd** [comment]
Old issue: https://github.com/allenai/reviz/issues/172

**Comment by codeviking** [comment]
Of note, today we ran into a bit of an issue related to the integration of model cards into the UI.

The AllenNLP platform team has expressed a desire to migrate away from model ids that don't include the task. For instance, instead of using an id like `bidaf`, the id will be `rc-bidaf`, where `rc` indicates the task that the model was trained for.

This change was already made in the API that returns information about model cards. This means we can't lookup the model card for a model, unless we know the id in the new format.  Some models in the demo already have this, in a field called `pretrained_model_id`, but others (like the NMN model) do not.

I put some [duct-tape in place today](https://github.com/allenai/allennlp-demo/blob/master/ui/src/components/MultiModelDemo.tsx#L36) to unblock @jonborchardt, but neither of us think we should maintain this solution, as we'll just be doing more of this as we convert additional tasks, or as we add new, similar models to the demo in the future.

Instead we'd like to migrate the demo to use the new id format, though this introduces some unexpected work. But first, some context.

The existing endpoints are of the form `/api/:model-id`, where `:model-id` is of the old form (i.e. `bidaf`).  These URLs are hard-coded throughout the existing demos, which means it'd be hard to update them in a single pass without breaking things (as it's a lot to test!).  Instead we'd like to do a more iterative migration:

Step 1: We'll add a new field, `alt_ids` to each `model.json`. We'll update each `model.json` to use the new id format, and add the old id to `alt_ids`:

```diff
# api/allennlp_demo/bidaf/model.json
{
-  id: 'bidaf'
+ id: 'rc-bidaf'
+ alt_ids: [ 'bidaf' ]
}
```

As part of this step we'll patch the Kubernetes config so that each endpoint handles `/api/:id` and `/api/:alt_id for alt_id in alt_ids`.  This way both `/api/bidaf` and `/api/rc-bidaf` will work.

We'll also update the directory name (`bidaf`) to `rc-bidaf` and any references to it for consistency. This will involve a little work as the Skiiff triggers also use the old name.

Step 2: New demos will use the new id when querying the API, whereas we won't touch old demos (since the old path should continue to work).

Step 3: After we're done porting over demos, we can remove `alt_ids`, since there won't be any code using it anymore.

I think it'll take 2-3 days to do the migration proposed in Step 1.  There's a few Marina changes I need to make for Hillel first, but I can start these changes after that.  It'll just delay the Milton Integration and Skiff Cluster Backup work that's in the hopper for me now.

**Comment by codeviking** [comment]
On second thought, I think I won't change module paths right now in the Python code to match the new naming convention. The issue is that names like `rc-bidaf_elmo` don't translate well, since it'd have to become `rc_bidaf_elmo`. It's also more work, and probably not worth it right now.

**Comment by jonborchardt** [comment]
this makes sense.  i have some ideas i put in external thread.  if they pan out, ill move them here.

**Comment by codeviking** [comment]
I think we need to do this too: 
https://gist.github.com/codeviking/e69df59f664380276a21efec8337478e
